### ISSUE TITLE
investigate failure in gtfs etl to extract 2022/02/03/TripIdToDate.zip

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus-gtfs-etl#16]
https://open-bus-airflow.hasadna.org.il/log?dag_id=gtfs-etl&task_id=extract&execution_date=2022-02-02T00%3A00%3A00%2B00%3A00

```
/srv/bin/pip_install_deps.sh && /usr/local/lib/stride/bin/python -u /srv/open_bus_pipelines/operators/_api_bash_operator_script.py '{"type": "cli", "module": "open_bus_gtfs_etl.cli", "function": "extract", "kwargs": {"date": {}, "workdir": {}}}' '{}'
[2022-02-03 00:00:35,803] {bash.py:169} INFO - Output:
[2022-02-03 00:00:35,806] {bash.py:173} INFO - {}
[2022-02-03 00:00:35,808] {bash.py:173} INFO - waiting for lock
[2022-02-03 00:00:35,809] {bash.py:173} INFO - lock acquired
[2022-02-03 00:00:36,128] {bash.py:173} INFO - 1
[2022-02-03 00:00:36,130] {bash.py:173} INFO - 1
[2022-02-03 00:00:36,130] {bash.py:173} INFO - Using existing open-bus-pipelines dependencies: edc186819c45c761f97d2fc9ed9e36f29ad78455
[2022-02-03 00:00:36,157] {bash.py:173} INFO - config: {"type": "cli", "module": "open_bus_gtfs_etl.cli", "function": "extract", "kwargs": {"date": {}, "workdir": {}}}
[2022-02-03 00:00:36,158] {bash.py:173} INFO - dag_run_conf: {}
[2022-02-03 00:00:37,481] {bash.py:173} INFO - invoking cli function with kwargs: {'date': None, 'workdir': None}
[2022-02-03 00:00:37,482] {bash.py:173} INFO - Extracting GTFS data for date 2022-02-03 to workdir /var/gtfs-storage/workdir
[2022-02-03 00:00:37,587] {bash.py:173} INFO - Archive:  /var/gtfs-storage/gtfs_archive/2022/02/03/israel-public-transportation.zip
[2022-02-03 00:00:37,590] {bash.py:173} INFO -   inflating: agency.txt
[2022-02-03 00:00:37,603] {bash.py:173} INFO -   inflating: calendar.txt
[2022-02-03 00:00:37,606] {bash.py:173} INFO -   inflating: fare_attributes.txt
[2022-02-03 00:00:37,805] {bash.py:173} INFO -   inflating: fare_rules.txt
[2022-02-03 00:00:37,821] {bash.py:173} INFO -   inflating: routes.txt
[2022-02-03 00:00:40,198] {bash.py:173} INFO -   inflating: shapes.txt
[2022-02-03 00:00:43,698] {bash.py:173} INFO -   inflating: stop_times.txt
[2022-02-03 00:00:43,783] {bash.py:173} INFO -   inflating: stops.txt
[2022-02-03 00:00:43,975] {bash.py:173} INFO -   inflating: translations.txt
[2022-02-03 00:00:44,109] {bash.py:173} INFO -   inflating: trips.txt
[2022-02-03 00:00:44,134] {bash.py:173} INFO - Archive:  /var/gtfs-storage/gtfs_archive/2022/02/03/Tariff.zip
[2022-02-03 00:00:44,163] {bash.py:173} INFO -   inflating: StationToReformZone.txt
[2022-02-03 00:00:44,174] {bash.py:173} INFO -   inflating: Tariff.txt
[2022-02-03 00:00:44,206] {bash.py:173} INFO - Archive:  /var/gtfs-storage/gtfs_archive/2022/02/03/ClusterToLine.zip
[2022-02-03 00:00:44,234] {bash.py:173} INFO -   inflating: ClusterToLine.txt
[2022-02-03 00:00:44,294] {bash.py:173} INFO - Archive:  /var/gtfs-storage/gtfs_archive/2022/02/03/TripIdToDate.zip
[2022-02-03 00:00:44,294] {bash.py:173} INFO -   End-of-central-directory signature not found.  Either this file is not
[2022-02-03 00:00:44,294] {bash.py:173} INFO -   a zipfile, or it constitutes one disk of a multi-part archive.  In the
[2022-02-03 00:00:44,294] {bash.py:173} INFO -   latter case the central directory and zipfile comment will be found on
[2022-02-03 00:00:44,294] {bash.py:173} INFO -   the last disk(s) of this archive.
[2022-02-03 00:00:44,298] {bash.py:173} INFO - unzip:  cannot find zipfile directory in one of /var/gtfs-storage/gtfs_archive/2022/02/03/TripIdToDate.zip or
[2022-02-03 00:00:44,298] {bash.py:173} INFO -         /var/gtfs-storage/gtfs_archive/2022/02/03/TripIdToDate.zip.zip, and cannot find /var/gtfs-storage/gtfs_archive/2022/02/03/TripIdToDate.zip.ZIP, period.
[2022-02-03 00:00:44,299] {bash.py:173} INFO - Traceback (most recent call last):
[2022-02-03 00:00:44,299] {bash.py:173} INFO -   File "/srv/open_bus_pipelines/operators/_api_bash_operator_script.py", line 27, in <module>
[2022-02-03 00:00:44,299] {bash.py:173} INFO -     main(*sys.argv[1:])
[2022-02-03 00:00:44,299] {bash.py:173} INFO -   File "/srv/open_bus_pipelines/operators/_api_bash_operator_script.py", line 18, in main
[2022-02-03 00:00:44,299] {bash.py:173} INFO -     function.callback(**kwargs)
[2022-02-03 00:00:44,299] {bash.py:173} INFO -   File "/usr/local/lib/stride/lib/python3.8/site-packages/open_bus_gtfs_etl/cli.py", line 43, in extract
[2022-02-03 00:00:44,299] {bash.py:173} INFO -     extract_api.main(**kwargs)
[2022-02-03 00:00:44,299] {bash.py:173} INFO -   File "/usr/local/lib/stride/lib/python3.8/site-packages/open_bus_gtfs_etl/extract.py", line 27, in main
[2022-02-03 00:00:44,299] {bash.py:173} INFO -     subprocess.check_call(['unzip', zip_file_name], cwd=extracted_path)
[2022-02-03 00:00:44,299] {bash.py:173} INFO -   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
[2022-02-03 00:00:44,299] {bash.py:173} INFO -     raise CalledProcessError(retcode, cmd)
[2022-02-03 00:00:44,300] {bash.py:173} INFO - subprocess.CalledProcessError: Command '['unzip', PosixPath('/var/gtfs-storage/gtfs_archive/2022/02/03/TripIdToDate.zip')]' returned non-zero exit status 9.
[2022-02-03 00:00:44,647] {bash.py:177} INFO - Command exited with return code 1
[2022-02-03 00:00:44,679] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/srv/open_bus_pipelines/operators/api_bash_operator.py", line 24, in execute
    return super(ApiBashOperator, self).execute(context)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-02-03 00:00:44,681] {taskinstance.py:1525} INFO - Marking task as FAILED. dag_id=gtfs-etl, task_id=extract, execution_date=20220202T000000, start_date=20220203T000035, end_date=20220203T000044
```

**Comment by OriHoch** [comment]
https://open-bus-gtfs-data.hasadna.org.il/gtfs_archive/2022/02/03/TripIdToDate.zip

**Comment by OriHoch** [comment]
looks like it was a temporary bug in the download from MOT, re-run of the dag fixed it - https://open-bus-airflow.hasadna.org.il/log?dag_id=gtfs-etl&task_id=extract&execution_date=2022-02-03T06%3A57%3A31.196077%2B00%3A00

**Comment by OriHoch** [comment]
opened an issue to fix such problems in the future - https://github.com/hasadna/open-bus-gtfs-etl/issues/17
